openapi: 3.0.0
info:
  title: POC API RESTFULL
  version: "1.0.0"
  description: Documentação da POC API RESTFULL
servers:
  - url: http://localhost:8080
    description: Servidor de desenvolvimento
paths:
  /signup:
    post:
      summary: Cria um novo usuário
      description: Cria um novo usuário no sistema.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUser'
      responses:
        "201":
          description: Usuário criado com sucesso.
        "400":
          description: Requisição inválida.
  /signin:
    post:
      summary: Autentica o usuário
      description: Realiza autenticação e retorna um token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUser'
      responses:
        "200":
          description: Usuário autenticado com sucesso.
        "401":
          description: Credenciais inválidas.
  "/":
    get:
      summary: Recupera o usuário logado
      description: Retorna os dados do usuário autenticado.
      responses:
        "200":
          description: Dados do usuário.
        "404":
          description: Usuário não encontrado.
  "/{id}":
    get:
      summary: Recupera um usuário pelo ID
      description: Retorna os dados do usuário a partir do ID fornecido.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: O ID do usuário.
      responses:
        "200":
          description: Dados do usuário.
        "404":
          description: Usuário não encontrado.
    patch:
      summary: Atualiza um usuário
      description: Atualiza as informações do usuário a partir do ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: O ID do usuário.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Usuário atualizado com sucesso.
        "400":
          description: Requisição inválida.
    delete:
      summary: Deleta um usuário
      description: Remove um usuário do sistema.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: O ID do usuário.
      responses:
        "200":
          description: Usuário deletado com sucesso.
        "404":
          description: Usuário não encontrado.
components:
  schemas:
    CreateUser:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      required:
        - name
        - email
        - password
    LoginUser:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password