@baseUrl = http://localhost:8080

# @name Health Check
GET {{baseUrl}}/
Content-Type: application/json
Accept: application/json

###

# @name Options Users
OPTIONS {{baseUrl}}/users
Content-Type: application/json
Accept: application/json

###

# @name Signup
POST {{baseUrl}}/users/signup
Content-Type: application/json
Accept: application/json
Origin: http://localhost:8080

{
    "name": "Santiago",
    "email": "santiago@santiago.com",
    "password": "123456"
}

###

# @name Signin
POST {{baseUrl}}/users/signin
Content-Type: application/json
Accept: application/json
Origin: http://localhost:8080

{
    "email": "teste@teste.com",
    "password": "123456"
}

###

# @name Get User by Token (rota protegida)
GET {{baseUrl}}/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer <coloque_seu_token_aqui>

###

# @name Get User by ID (rota protegida)
GET {{baseUrl}}/users/<USER_ID>
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjEwMjBiOWFmYTg1MGZlMmM1MzBhMyIsImVtYWlsIjoidGVzdGVAdGVzdGUuY29tIiwiaWF0IjoxNzM5NjUzNzc1LCJleHAiOjE3Mzk3NDAxNzV9.OVNvfkhKISo10tiysPWQEv3MVRuFzJODMKdayBnpBQs

###

# @name Update User (rota protegida)
PATCH {{baseUrl}}/users/<USER_ID>
Content-Type: application/json
Accept: application/json
Authorization: Bearer <coloque_seu_token_aqui>

{
    "name": "Novo Nome",
    "email": "novoteste@teste.com"
}

###

# @name Delete User (rota protegida)
DELETE {{baseUrl}}/users/<USER_ID>
Content-Type: application/json
Accept: application/json
Authorization: Bearer <coloque_seu_token_aqui>

###