@baseUrl = http://localhost:8080

# @name Health Check
GET {{baseUrl}}/
Content-Type: application/json
Accept: application/json

###

# @name Options Users
OPTIONS {{baseUrl}}/users
Content-Type: application/json
Accept: application/json

###

# @name Signup
POST {{baseUrl}}/users/signup
Content-Type: application/json
Accept: application/json
Origin: http://localhost:8080

{
    "name": "Santiago",
    "email": "santiago@santiago.com",
    "password": "123456"
}

###

# @name Signin
POST {{baseUrl}}/users/signin
Content-Type: application/json
Accept: application/json
Origin: http://localhost:8080

{
    "email": "santiago@santiago.com",
    "password": "123456"
}

###

# @name Get User by Token (rota protegida)
GET {{baseUrl}}/users
Content-Type: application/json
Origin: http://localhost:8080
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjExZGJlZjQxNmI3ZjRjMjczMzI5OCIsImVtYWlsIjoic2FudGlhZ29Ac2FudGlhZ28uY29tIiwiaWF0IjoxNzM5NjYwNzY5LCJleHAiOjE3Mzk3NDcxNjl9.YIJ1292HutbgPPs18fwF_yd_17jpee88jPJ6TSwXMsw

###

# @name Get User by ID (rota protegida)
GET {{baseUrl}}/users/67b11dbef416b7f4c2733298
Content-Type: application/json
Accept: application/json
Origin: http://localhost:8080
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjExZGJlZjQxNmI3ZjRjMjczMzI5OCIsImVtYWlsIjoic2FudGlhZ29Ac2FudGlhZ28uY29tIiwiaWF0IjoxNzM5NjYwNzY5LCJleHAiOjE3Mzk3NDcxNjl9.YIJ1292HutbgPPs18fwF_yd_17jpee88jPJ6TSwXMsw

###

# @name Update User (rota protegida)
PATCH {{baseUrl}}/users/67b11dbef416b7f4c2733298
Content-Type: application/json
Accept: application/json
Origin: http://localhost:8080
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjExZGJlZjQxNmI3ZjRjMjczMzI5OCIsImVtYWlsIjoic2FudGlhZ29Ac2FudGlhZ28uY29tIiwiaWF0IjoxNzM5NjYwNzY5LCJleHAiOjE3Mzk3NDcxNjl9.YIJ1292HutbgPPs18fwF_yd_17jpee88jPJ6TSwXMsw

{
    "name": "Rafael silva santiago"
}

###

# @name Delete User (rota protegida)
DELETE {{baseUrl}}/users/<USER_ID>
Content-Type: application/json
Accept: application/json
Authorization: Bearer <coloque_seu_token_aqui>

###