FROM node:20.11.1-slim

RUN apt update && \
    npm install -y -g nodemon

COPY start.sh /
RUN chmod +x /start.sh

USER node

EXPOSE 3000

WORKDIR /home/node/app

COPY --chown=node:node package*.json .
RUN npm install

COPY --chown=node:node . .

CMD [ "/start.sh" ]